### ISSUE TITLE
The bundle “PIC Assembly” could not be installed because it is in delta format.

### ISSUE THREAD

**Issue by stormbytes** [morrowa/pic-assembly-textmate-bundle#4]
Getting this on TM2 when trying to install the bundle.

Not loading any which way....... ;(

**Comment by morrowa** [comment]
Sorry, this repository is now unmaintained. I haven't used TextMate in at least six years and have no plans to resume.

Check out the very active forks which have taken this nearly empty project and made it into something much bigger.
